import {normalize,personText,buildGedcom,downloadText} from './data-loader.js';
import {createPreview} from './admin-preview.js?v=20260715-6';
import {publishChanges} from './publisher.js';
const $=selector=>document.querySelector(selector),ids=value=>String(value||'').split(',').map(item=>item.trim()).filter(Boolean),nextId=(prefix,items)=>prefix+(Math.max(0,...items.map(item=>Number(item.id.slice(1))||0))+1);

export function startEditor(family,layout){
  const state={family,layout,tab:'people',selectedPerson:null,selectedRelation:null,drag:null};
  const fields={pid:$('#person-id'),pname:$('#person-name'),pdetails:$('#person-details'),bplace:$('#birth-place'),bdate:$('#birth-date'),dplace:$('#death-place'),ddate:$('#death-date'),parents:$('#person-parents'),notes:$('#person-notes'),focus:$('#person-focus'),prender:$('#person-render'),x:$('#pos-x'),y:$('#pos-y'),w:$('#pos-w'),h:$('#pos-h'),rid:$('#relation-id'),rtype:$('#relation-type'),rplace:$('#relation-place'),rdate:$('#relation-date'),rlabel:$('#relation-label'),partners:$('#relation-partners'),children:$('#relation-children'),rrender:$('#relation-render'),rx:$('#rel-x'),ry:$('#rel-y')};
  let preview;
  function list(){const box=$('#library-list');box.replaceChildren();const query=normalize($('#library-search').value),items=state.tab==='people'?state.family.people:state.family.relationships;for(const item of items.filter(entry=>normalize(state.tab==='people'?personText(entry):`${entry.id} ${entry.label} ${entry.place} ${entry.date}`).includes(query))){const button=document.createElement('button');button.className='library-item';const active=state.tab==='people'?item.id===state.selectedPerson?.id:item.id===state.selectedRelation?.id;if(active)button.classList.add('active');button.innerHTML='<strong></strong><small></small>';button.querySelector('strong').textContent=state.tab==='people'?item.name:`${item.id} · ${item.type}`;button.querySelector('small').textContent=state.tab==='people'?(item.details||[]).join(' · '):String(item.label||'').replace(/\n/g,' · ');button.onclick=()=>state.tab==='people'?selectPerson(item.id):selectRelation(item.id);box.append(button)}}
  function selectPerson(id){state.selectedPerson=state.family.people.find(item=>item.id===id)||null;state.selectedRelation=null;$('#person-editor').hidden=false;$('#relation-editor').hidden=true;const person=state.selectedPerson;if(!person)return;const box=state.layout.people[id]||{x:100,y:100,width:130,height:38};fields.pid.value=person.id;fields.pname.value=person.name||'';fields.pdetails.value=(person.details||[]).join('\n');fields.bplace.value=person.birth?.place||'';fields.bdate.value=person.birth?.date||'';fields.dplace.value=person.death?.place||'';fields.ddate.value=person.death?.date||'';fields.parents.value=(person.parents||[]).join(', ');fields.notes.value=person.notes||'';fields.focus.checked=!!person.focus;fields.prender.checked=!!person.renderLabel;fields.x.value=box.x;fields.y.value=box.y;fields.w.value=box.width;fields.h.value=box.height;$('#person-title').textContent=person.name;for(const id of ['save-person','delete-person','center-selected'])$('#'+id).disabled=false;list();preview.render()}
  function selectRelation(id){state.selectedRelation=state.family.relationships.find(item=>item.id===id)||null;state.selectedPerson=null;$('#person-editor').hidden=true;$('#relation-editor').hidden=false;const relation=state.selectedRelation;if(!relation)return;const point=state.layout.relationships[id]||{x:100,y:100};fields.rid.value=relation.id;fields.rtype.value=relation.type;fields.rplace.value=relation.place||'';fields.rdate.value=relation.date||'';fields.rlabel.value=relation.label||'';fields.partners.value=(relation.partners||[]).join(', ');fields.children.value=(relation.children||[]).join(', ');fields.rrender.checked=!!relation.renderLabel;fields.rx.value=point.x;fields.ry.value=point.y;$('#relation-title').textContent=`${relation.id} · ${relation.type}`;for(const id of ['save-relation','delete-relation','center-relation'])$('#'+id).disabled=false;list();preview.render()}
  function savePerson(){const person=state.selectedPerson;if(!person)return;Object.assign(person,{name:fields.pname.value.trim(),details:fields.pdetails.value.split('\n').map(item=>item.trim()).filter(Boolean),birth:{place:fields.bplace.value.trim(),date:fields.bdate.value.trim()},death:{place:fields.dplace.value.trim(),date:fields.ddate.value.trim()},parents:ids(fields.parents.value),notes:fields.notes.value.trim(),focus:fields.focus.checked,renderLabel:fields.prender.checked});state.layout.people[person.id]={x:+fields.x.value||0,y:+fields.y.value||0,width:+fields.w.value||130,height:+fields.h.value||38};selectPerson(person.id)}
  function saveRelation(){const relation=state.selectedRelation;if(!relation)return;Object.assign(relation,{type:fields.rtype.value,place:fields.rplace.value.trim(),date:fields.rdate.value.trim(),label:fields.rlabel.value.trim(),partners:ids(fields.partners.value),children:ids(fields.children.value),renderLabel:fields.rrender.checked});state.layout.relationships[relation.id]={x:+fields.rx.value||0,y:+fields.ry.value||0};selectRelation(relation.id)}
  function addPerson(){const id=nextId('p',state.family.people);state.family.people.push({id,name:'Nova persona',details:[],birth:{place:'',date:''},death:{place:'',date:''},parents:[],notes:'',focus:false,renderLabel:true});state.layout.people[id]={x:state.layout.canvas.width*.75,y:state.layout.canvas.height*.85,width:140,height:40};state.tab='people';selectPerson(id)}
  function addRelation(){const id=nextId('r',state.family.relationships);state.family.relationships.push({id,type:'married',label:'⚭',partners:[],children:[],place:'',date:'',renderLabel:true});state.layout.relationships[id]={x:state.layout.canvas.width*.75,y:state.layout.canvas.height*.85};state.tab='relations';selectRelation(id)}
  function deletePerson(){const person=state.selectedPerson;if(!person||!confirm(`Eliminar ${person.name}?`))return;state.family.people=state.family.people.filter(item=>item.id!==person.id);delete state.layout.people[person.id];for(const relation of state.family.relationships){relation.partners=(relation.partners||[]).filter(id=>id!==person.id);relation.children=(relation.children||[]).filter(id=>id!==person.id)}state.selectedPerson=null;list();preview.render()}
  function deleteRelation(){const relation=state.selectedRelation;if(!relation||!confirm(`Eliminar ${relation.id}?`))return;state.family.relationships=state.family.relationships.filter(item=>item.id!==relation.id);delete state.layout.relationships[relation.id];state.selectedRelation=null;list();preview.render()}
  preview=createPreview($('#preview-svg'),state,selectPerson,{x:fields.x,y:fields.y});preview.bindDrag();preview.render();
  document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{state.tab=button.dataset.tab;document.querySelectorAll('[data-tab]').forEach(item=>item.classList.toggle('active',item===button));list()});$('#library-search').oninput=list;$('#save-person').onclick=savePerson;$('#save-relation').onclick=saveRelation;$('#new-person').onclick=addPerson;$('#new-relation').onclick=addRelation;$('#delete-person').onclick=deletePerson;$('#delete-relation').onclick=deleteRelation;$('#center-selected').onclick=()=>preview.center(state.layout.people[state.selectedPerson.id]);$('#center-relation').onclick=()=>{const point=state.layout.relationships[state.selectedRelation.id];preview.center({x:point.x-10,y:point.y-10,width:20,height:20})};$('#preview-fit').onclick=preview.fit;$('#export-family').onclick=()=>downloadText('family.json',JSON.stringify(state.family,null,2)+'\n');$('#export-layout').onclick=()=>downloadText('layout.json',JSON.stringify(state.layout,null,2)+'\n');$('#export-gedcom').onclick=()=>downloadText('somcomsom.ged',buildGedcom(state.family),'text/plain');$('#publish-github').onclick=()=>publishChanges(state.family,state.layout);selectPerson(state.family.people.find(item=>item.focus)?.id||state.family.people[0]?.id)
}
